# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

c.statusbar.position = 'top' 

# hidpi
# c.qt.highdpi = true
c.zoom.default = 142

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Allow websites to request geolocations.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.geolocation', True, 'https://g1.globo.com')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications', True, 'https://www.youtube.com')

# Hide the statusbar unless a message is shown.
# Type: Bool
c.statusbar.show = 'never'

# Mouse button with which to close tabs.
# Type: String
# Valid values:
#   - right: Close tabs on right-click.
#   - middle: Close tabs on middle-click.
#   - none: Don't close tabs using the mouse.
c.tabs.close_mouse_button = 'right'

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 2, 'left': 2, 'right': 2, 'top': 2}

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'top'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

# Alignment of the text inside of tabs.
# Type: TextAlignment
# Valid values:
#   - left
#   - right
#   - center
c.tabs.title.alignment = 'left'

# Width (in pixels or as percentage of the window) of the tab bar if
# it's vertical.
# Type: PercOrInt
c.tabs.width = '20%'

# Width (in pixels) of the progress indicator (0 to disable).
# Type: Int
c.tabs.indicator.width = 2

# Padding (in pixels) for tab indicators.
# Type: Padding
c.tabs.indicator.padding = {'bottom': 4, 'left': 4, 'right': 4, 'top': 4}

# Background color of the statusbar.
# Type: QssColor
# c.colors.statusbar.normal.bg = 'white'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
# c.fonts.monospace = '"Iosevka Term SS07" "xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", Fixed, Consolas, Terminal'
# c.fonts.monospace = 'Iosevka Term SS07'
c.fonts.default_family = 'Bold Iosevka Term SS07'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = 'Bold 11pt Iosevka Term SS07'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'Bold 11pt Iosevka Term SS07'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = 'Bold 10pt Iosevka Term SS07'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = 'Bold 10pt Iosevka Term SS07'

# Font used for the hints.
# Type: Font
c.fonts.hints = '10pt Iosevka Term SS07'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt Iosevka Term SS07'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt Iosevka Term SS07'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt Iosevka Term SS07'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt Iosevka Term SS07'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt Iosevka Term SS07'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt Iosevka Term SS07'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs.selected = 'Bold 11.25pt Iosevka Term SS07'
c.fonts.tabs.unselected = 'Bold 11.25pt Iosevka Term SS07'

# Default font size (in pixels) for Light text.
# Type: Int
c.fonts.web.size.default = 16

#import dracula.draw

# Load existing settings made via :set
#config.load_autoconfig()

#dracula.draw.blood(c, {
#    'spacing': {
#        'vertical': 2,
#        'horizontal': 2
#    }
#})

#script = $HOME/.config/qutebrowser/mpv.zsh
#config.bind('<r>', 'hint --mode number links spawn mpv {hint-url})')
config.bind('<c>', 'hint --mode number links yank')
# config.bind('<r>', 'hint --mode number links spawn mpv --title="YouTube-{hint-url}" {hint-url}')
#config.bind('<r>', 'hint --mode number links spawn mpv --x11-name="YouTube" {hint-url}')
# config.bind('<r>', 'spawn --userscript /usr/bin/mp')
config.bind('<r>', 'spawn /usr/bin/mp')
config.bind('<shift+r>', 'spawn --userscript /usr/bin/wq mpurl')
config.bind('<t>', 'hint --mode number links spawn smplayer -add-to-playlist QUTE_URL')
config.bind('<f>', 'hint --mode number')

def gruvbox():
	global base00
	global base01
	global base02
	global base03
	global base04
	global base05
	global base06
	global base07
	global base08
	global base09
	global base0A
	global base0B
	global base0C
	global base0D
	global base0E
	global base0F
	## gruvbox
	base00 = "#1d2021"
	base01 = "#3c3836"
	base02 = "#504945"
	base03 = "#797261"
	base04 = "#090c0d"
	base05 = "#d5c4a1"
	base06 = "#ebdbb2"
	base07 = "#efe7c5"
	base08 = "#f56352"
	base09 = "#fe8019"
	base0A = "#fabd2f"
	base0B = "#a4a700"
	base0C = "#7ba76c"
	base0D = "#7ebaa3"
	base0E = "#a17682"
	base0F = "#e55d21"

def materialdarker ():
	global base00
	global base01
	global base02
	global base03
	global base04
	global base05
	global base06
	global base07
	global base08
	global base09
	global base0A
	global base0B
	global base0C
	global base0D
	global base0E
	global base0F
	## material-darker
	base00 = "#212121"
	base01 = "#303030"
	base02 = "#353535"
	base03 = "#879090"
	base04 = "#0d0d0d"
	base05 = "#eeffff"
	base06 = "#eeffff"
	base07 = "#b9b9b9"
	base08 = "#f34a34"
	base09 = "#f78c6c"
	base0A = "#ffcb6b"
	base0B = "#9ea102"
	base0C = "#4acaff"
	base0D = "#2882f9"
	base0E = "#daa0ff"
	base0F = "#e0573c"

gruvbox()

# set qutebrowser colors

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
c.colors.completion.fg = base05

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = base03

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = base00

# Foreground color of completion widget category headers.
c.colors.completion.category.fg = base0A

# Background color of the completion widget category headers.
c.colors.completion.category.bg = base00

# Top border color of the completion widget category headers.
c.colors.completion.category.border.top = base00

# Bottom border color of the completion widget category headers.
c.colors.completion.category.border.bottom = base00

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = base01

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = base0D

# Top border color of the selected completion item.
c.colors.completion.item.selected.border.top = base0A

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = base0A

# Foreground color of the matched text in the selected completion item.
c.colors.completion.item.selected.match.fg = base08

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = base0B

# Color of the scrollbar handle in the completion view.
c.colors.completion.scrollbar.fg = base05

# Color of the scrollbar in the completion view.
c.colors.completion.scrollbar.bg = base00

# Background color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.bg = base00

# Foreground color of the context menu. If set to null, the Qt default is used.
c.colors.contextmenu.menu.fg =  base05

# Background color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.bg = base0A

#Foreground color of the context menu’s selected item. If set to null, the Qt default is used.
c.colors.contextmenu.selected.fg = base01

# Background color for the download bar.
c.colors.downloads.bar.bg = base00

# Color gradient start for download text.
c.colors.downloads.start.fg = base00

# Color gradient start for download backgrounds.
c.colors.downloads.start.bg = base0D

# Color gradient end for download text.
c.colors.downloads.stop.fg = base00

# Color gradient stop for download backgrounds.
c.colors.downloads.stop.bg = base0C

# Foreground color for downloads with errors.
c.colors.downloads.error.fg = base08

# Font color for hints.
c.colors.hints.fg = base00

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
c.colors.hints.bg = base0A

# Font color for the matched part of hints.
c.colors.hints.match.fg = base05

# Text color for the keyhint widget.
c.colors.keyhint.fg = base05

# Highlight color for keys to complete the current keychain.
c.colors.keyhint.suffix.fg = base05

# Background color of the keyhint widget.
c.colors.keyhint.bg = base00

# Foreground color of an error message.
c.colors.messages.error.fg = base00

# Background color of an error message.
c.colors.messages.error.bg = base08

# Border color of an error message.
c.colors.messages.error.border = base08

# Foreground color of a warning message.
c.colors.messages.warning.fg = base00

# Background color of a warning message.
c.colors.messages.warning.bg = base0E

# Border color of a warning message.
c.colors.messages.warning.border = base0E

# Foreground color of an info message.
c.colors.messages.info.fg = base05

# Background color of an info message.
c.colors.messages.info.bg = base00

# Border color of an info message.
c.colors.messages.info.border = base00

# Foreground color for prompts.
c.colors.prompts.fg = base05

# Border used around UI elements in prompts.
c.colors.prompts.border = base00

# Background color for prompts.
c.colors.prompts.bg = base00

# Background color for the selected item in filename prompts.
c.colors.prompts.selected.bg = base0A

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = base0B

# Background color of the statusbar.
c.colors.statusbar.normal.bg = base00

# Foreground color of the statusbar in insert mode.
c.colors.statusbar.insert.fg = base00

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = base0D

# Foreground color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.fg = base00

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = base0C

# Foreground color of the statusbar in private browsing mode.
c.colors.statusbar.private.fg = base00

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = base03

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = base05

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = base00

# Foreground color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.fg = base05

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = base00

# Foreground color of the statusbar in caret mode.
c.colors.statusbar.caret.fg = base00

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = base0E

# Foreground color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.fg = base00

# Background color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.bg = base0D

# Background color of the progress bar.
c.colors.statusbar.progress.bg = base0D

# Default foreground color of the URL in the statusbar.
c.colors.statusbar.url.fg = base05

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = base08

# Foreground color of the URL in the statusbar for hovered links.
c.colors.statusbar.url.hover.fg = base05

# Foreground color of the URL in the statusbar on successful load
# (http).
c.colors.statusbar.url.success.http.fg = base0C

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = base0B

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = base0E

# Background color of the tab bar.
c.colors.tabs.bar.bg = base00

# Color gradient start for the tab indicator.
c.colors.tabs.indicator.start = base0D

# Color gradient end for the tab indicator.
c.colors.tabs.indicator.stop = base0C

# Color for the tab indicator on errors.
c.colors.tabs.indicator.error = base08

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = base05

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = base00

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = base05

# Background color of unselected even tabs.
c.colors.tabs.even.bg = base00

# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = base00

# Foreground color of pinned unselected even tabs.
c.colors.tabs.pinned.even.fg = base07

# Background color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.bg = base00

# Foreground color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.fg = base07

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = base00

# Foreground color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.fg = base00

# Background color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.bg = base00

# Foreground color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.fg = base0E

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = base00

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = base0D

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = base00

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = base0D
