#!/bin/zsh
 #. "${HOME}/.cache/wal/colors.sh"
declare -gx path_dots=$HOME/hdbkp/dots
declare -gx path_scripts=$path_dots/scripts
declare -gx path_polybar=$path_dots/polybar
declare -gx path_colors=$path_dots/temas
. $path_scripts/shell.zsh
. $path_colors/colors.zsh
export colorgreen="#2CD776"
export color_focused_border_color
export color_normal_border_color="#333333"
export color_active_border_color="#333333"
export color_presel_feedback_color="#333333"
export TERM="xterm-256color"
export LANG="pt_BR.UTF-8"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QUTEWAL_DYNAMIC_LOADING="True"
export XDG_CONFIG_HOME="$HOME/.config"
export PATH="${HOME}/.local/bin:${HOME}/.local/share/virtualenvs/qutewal-8OrCaHwS/bin/activate:${PATH}"
export monitor1=$(xrandr |grep ' connected'|sed -n 1p|awk '{print $1}'); echo $monitor1 > /tmp/monitor1
export monitor2=$(xrandr |grep ' connected'|sed -n 2p|awk '{print $1}'); echo $monitor2 > /tmp/monitor2
xrandr --output "$monitor1" --mode 2560x1440 --dpi 96 --primary
bspc monitor "$monitor1" -d 1 2 3 4 5 6 7 8 9
hsetroot -solid "$(echo "$background" |tr 'a-z' 'A-Z')"
nitrogen --restore &
sxhkd &
lxqt-policykit-agent &

bspc config remove_disabled_monitors true
bspc config ignore_ewmh_focus true
bspc config honor_size_hints false
bspc config split_ratio 0.5
bspc config border_width 4
bspc config window_gap 0
bspc config focused_border_color $color1
bspc config normal_border_color $background || bspc config normal_border_color $color_normal_border_color
bspc config active_border_color $background || bspc config normal_border_color $color_active_border_color
bspc config presel_feedback_color $background || bspc config normal_border_color $color_presel_feedback_color
bspc config status_prefix true
bspc rule -a XTerm state=floating follow=off center=false sticky=off
bspc rule -a kitty state=floating follow=off center=false sticky=off
bspc rule -a tilda state=floating follow=on center=false sticky=on
bspc rule -a Alacritty state=floating follow=off center=false sticky=off
bspc rule -a Termite state=floating follow=on center=false sticky=off
bspc rule -a Yad state=floating #follow=off center=false sticky=off
bspc rule -a qutebrowser state=floating follow=on center=false sticky=off
bspc rule -a Google-chrome state=floating follow=on center=false sticky=off
bspc rule -a Pulseaudio-equalizer-gtk state=floating follow=on center=false sticky=off
bspc rule -a Nitrogen state=floating follow=on center=false
bspc rule -a Atom state=floating follow=on center=false
bspc rule -a Subl3 state=floating follow=on center=false
bspc rule -a Pamac-manager state=floating follow=on center=false
bspc rule -a Manjaro Settings Manager state=floating follow=on center=false
bspc rule -a Thunar state=floating follow=on center=false
bspc rule -a Nemo state=floating follow=on center=false
bspc rule -a nm-connection-editor state=floating follow=on center=false
bspc rule -a Nvidia-settings state=floating follow=on center=false
bspc rule -a qt5ct state=floating follow=on center=false
bspc rule -a Lxappearance state=floating follow=on center=false
bspc rule -a TelegramDesktop state=floating follow=on center=false
bspc rule -a whatsapp-nativefier-d52542 state=floating follow=on center=false
bspc rule -a smplayer state=floating follow=on center=false
bspc rule -a mpv state=floating follow=on center=true
bspc rule -a Xviewer state=floating follow=on center=false
bspc rule -a Nm-connection-editor state=floating follow=on center=false
bspc rule -a Pavucontrol state=floating follow=on center=true
bspc rule -a notifyconf state=floating follow=on center=true
bspc rule -a SimpleScreenRecorder state=floating follow=on center=false
bspc rule -a Code-oss #state=floating follow=on center=false
bspc rule -a Thunderbird state=floating follow=on center=false
bspc rule -a google-keep-nativefier-d04d04 state=floating follow=on center=false
picom --config ~/hdbkp/dots/picom.conf -b --experimental-backends &
#nvidia-settings -l --config ~/.nvidia-settings-rc &
wq launch &
pulseaudio-equalizer enable &
dunst &
wq keyboard.br &
wq weatcher start &
wq gpuinfo start &
taskbar start &
redshift-gtk &
lxappearance &
{ sleep 2 && taskbar close "$(</tmp/taskbar|grep --line-number lxapp| cut -d: -f1)" }
kitty 
sleep 1
tdrop -w 940 -h 400 -y 500 -x 500 -s dropdown --wm bspwm current
mp mpd
# sleep 2
# mpv &
