[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-gruvbox-dark-hard
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-gruvbox-dark-hard
GtkTheme=oomox-gruvbox-dark-hard
IconTheme=oomox-gruvbox-dark-hard
MetacityTheme=oomox-gruvbox-dark-hard
