" Name:         Eighties
" Description:  Dark color scheme with eighties pastel colors
" Author:       Chris Kempson
" Maintainer:   Peter Lithammer <peter.lithammer@gmail.com>
" Website:      https://github.com/lithammer/vim-eighties
" License:      MIT
" Last Updated: Fri Aug 16 15:22:35 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'eighties'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

let s:italics = s:italics && get(g:, 'eighties_italics', 1)
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Exception Statement
hi! link Float Constant
hi! link Number Constant
hi! link PreCondit PreProc
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link Substitute Search
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#2d2d2d', '#f2777a', '#99cc99', '#ffcc66',
        \ '#6699cc', '#cc99cc', '#66cccc', '#d3d0c8', '#747369', '#f2777a',
        \ '#99cc99', '#ffcc66', '#6699cc', '#cc99cc', '#66cccc', '#f2f0ec']
  if has('nvim')
    let g:terminal_color_0 = '#2d2d2d'
    let g:terminal_color_1 = '#f2777a'
    let g:terminal_color_2 = '#99cc99'
    let g:terminal_color_3 = '#ffcc66'
    let g:terminal_color_4 = '#6699cc'
    let g:terminal_color_5 = '#cc99cc'
    let g:terminal_color_6 = '#66cccc'
    let g:terminal_color_7 = '#d3d0c8'
    let g:terminal_color_8 = '#747369'
    let g:terminal_color_9 = '#f2777a'
    let g:terminal_color_10 = '#99cc99'
    let g:terminal_color_11 = '#ffcc66'
    let g:terminal_color_12 = '#6699cc'
    let g:terminal_color_13 = '#cc99cc'
    let g:terminal_color_14 = '#66cccc'
    let g:terminal_color_15 = '#f2f0ec'
  endif
  if get(g:, 'eighties_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d3d0c8 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d3d0c8 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#6699cc guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#2d2d2d guibg=#d3d0c8 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#a09f93 guibg=#393939 guisp=NONE gui=bold cterm=bold
  hi Debug guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#99cc99 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#f2777a guibg=#393939 guisp=NONE gui=bold cterm=bold
  hi DiffText guifg=#6699cc guibg=#393939 guisp=NONE gui=bold cterm=bold
  hi Directory guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#d3d0c8 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#f2777a guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#66cccc guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#393939 guibg=#f99157 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#747369 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#99cc99 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#747369 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Pmenu guifg=#d3d0c8 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#393939 guibg=#d3d0c8 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar ctermbg=248 guibg=Grey
  hi PmenuThumb ctermbg=15 guibg=White
  hi Question guifg=#6699cc guibg=NONE guisp=NONE gui=bold cterm=bold
  hi QuickFixLine guifg=NONE guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#393939 guibg=#ffcc66 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#f2777a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#6699cc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#cc99cc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#66cccc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#a09f93 guibg=#515151 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#747369 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#99cc99 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi TooLong guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#515151 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#515151 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#2d2d2d guibg=#ffcc66 guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#747369 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#f99157 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#d27b53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#2d2d2d guibg=#f2777a guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#d27b53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#99cc99 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Structure guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ffcc66 guibg=#393939 guisp=NONE gui=italic cterm=italic
  hi Type guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#f2777a guibg=NONE guisp=NONE gui=underline cterm=underline
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
  endif
  if !get(g:, 'eighties_italicize_strings', 1)
    hi String gui=NONE cterm=NONE
  endif
  hi ALEErrorSign guifg=#f2777a guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#f99157 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#66cccc guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextStyleError guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextStyleWarning guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cOperator guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cPreCondit guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csAttribute guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csClass guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csModifier guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewDecleration guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csType guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csUnspecifiedStatement guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssBraces guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassName guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssColor guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi diffAdded guifg=#99cc99 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi diffFile guifg=#f2777a guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi diffNewFile guifg=#99cc99 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi diffLine guifg=#6699cc guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#f2777a guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi gitcommitBranch guifg=#f99157 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitComment guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitDiscarded guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitDiscardedFile guifg=#f2777a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitDiscardedType guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitHeader guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitOverflow guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitSelected guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitSelectedFile guifg=#99cc99 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitSelectedType guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitSummary guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitUnmergedFile guifg=#f2777a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi gitcommitUnmergedType guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitUntracked guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi gitcommitUntrackedFile guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi GitGutterAdd guifg=#99cc99 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#6699cc guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#f2777a guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#cc99cc guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi htmlBold guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlItalic guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTag guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaOperator guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScript guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptBraces guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptNumber guifg=#f99157 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsBuiltins guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsClassDefinition guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsClassFuncName guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsClassMethodType guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsExceptions guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncCall guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncName guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunction guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalObjects guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsOperator guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsRegexpString guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsReturn guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsStatement guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsThis guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCodeBlock guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownError guifg=#d3d0c8 guibg=#2d2d2d guisp=NONE gui=NONE cterm=NONE
  hi markdownHeadingDelimiter guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpComparison guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMemberSelector guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMethodsVar guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpParent guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonInclude guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonOperator guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonRepeat guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonStatement guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyAttribute guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyConstant guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyInterpolationDelimiter guifg=#d27b53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyRegexp guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyStringDelimiter guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubySymbol guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClassChar guifg=#f99157 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassInclude guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassMixinName guifg=#6699cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassMixing guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassidChar guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiAttribute guifg=#d3d0c8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiBuiltin guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiErrorChar guifg=#2d2d2d guibg=#f2777a guisp=NONE gui=NONE cterm=NONE
  hi semshiErrorSign guifg=#f2777a guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi semshiFree guifg=#ffafd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiGlobal guifg=#d3d0c8 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi semshiImported guifg=#ffcc66 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiLocal guifg=#d27b53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiParameter guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiParameterUnused guifg=#87d7ff guibg=NONE guisp=NONE gui=underline cterm=underline
  hi semshiSelected guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi semshiSelf guifg=#f2777a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi semshiUnresolved guifg=#ffcc66 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SignifySignAdd guifg=#99cc99 guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#6699cc guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#f2777a guibg=#393939 guisp=NONE gui=NONE cterm=NONE
  hi StartifyBracket guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFile guifg=#f2f0ec guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyFooter guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyHeader guifg=#99cc99 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyNumber guifg=#f99157 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifyPath guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#cc99cc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySelect guifg=#66cccc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySlash guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySpecial guifg=#747369 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'eighties_transp_bg', 0)
    hi Normal ctermfg=7 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=7 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=7 cterm=NONE
    hi Terminal ctermfg=7 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=4 cterm=NONE
  hi Cursor ctermbg=7 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLineNr ctermfg=247 ctermbg=237 cterm=bold
  hi Debug ctermfg=1 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=2 ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=8 ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=1 ctermbg=237 cterm=bold
  hi DiffText ctermfg=4 ctermbg=237 cterm=bold
  hi Directory ctermfg=4 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=7 cterm=NONE
  hi ErrorMsg ctermfg=1 cterm=NONE
  hi FoldColumn ctermfg=6 ctermbg=237 cterm=NONE
  hi Folded ctermfg=8 ctermbg=237 cterm=NONE
  hi Function ctermfg=4 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=237 ctermbg=209 cterm=NONE
  hi LineNr ctermfg=8 ctermbg=237 cterm=NONE
  hi Macro ctermfg=1 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=8 cterm=NONE
  hi ModeMsg ctermfg=2 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=2 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=8 ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=7 ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=237 ctermbg=7 cterm=NONE
  hi PmenuSbar ctermbg=248 guibg=Grey
  hi PmenuThumb ctermbg=15 guibg=White
  hi Question ctermfg=4 ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi Search ctermfg=237 ctermbg=3 cterm=NONE
  hi SignColumn ctermfg=8 ctermbg=237 cterm=NONE
  hi SpecialKey ctermfg=8 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=247 ctermbg=239 cterm=NONE
  hi StatusLineNC ctermfg=8 ctermbg=237 cterm=NONE
  hi TabLine ctermfg=8 ctermbg=237 cterm=NONE
  hi TabLineFill ctermfg=8 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=2 ctermbg=237 cterm=NONE
  hi TooLong ctermfg=1 ctermbg=NONE cterm=NONE
  hi Title ctermfg=4 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=239 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=239 cterm=NONE
  hi VisualNOS ctermfg=1 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=1 ctermbg=NONE cterm=NONE
  hi WildMenu ctermbg=3 cterm=NONE
  hi Character ctermfg=1 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=8 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=5 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=209 ctermbg=NONE cterm=NONE
  hi Define ctermfg=5 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=166 ctermbg=NONE cterm=NONE
  hi Error ctermbg=1 cterm=NONE
  hi Identifier ctermfg=1 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=7 ctermbg=NONE cterm=NONE
  hi Include ctermfg=4 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=5 ctermbg=NONE cterm=NONE
  hi Label ctermfg=3 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=7 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=3 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=3 ctermbg=NONE cterm=NONE
  hi Special ctermfg=6 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=166 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=1 ctermbg=NONE cterm=NONE
  hi String ctermfg=2 ctermbg=NONE cterm=italic
  hi Structure ctermfg=5 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=3 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=3 ctermbg=237 cterm=italic
  hi Type ctermfg=3 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=1 ctermbg=NONE cterm=underline
  if !s:italics
    hi Comment cterm=NONE
    hi String cterm=NONE
    hi Todo cterm=NONE
  endif
  if !get(g:, 'eighties_italicize_strings', 1)
    hi String gui=NONE cterm=NONE
  endif
  hi ALEErrorSign ctermfg=1 ctermbg=237 cterm=NONE
  hi ALEWarningSign ctermfg=209 ctermbg=237 cterm=NONE
  hi ALEInfoSign ctermfg=6 ctermbg=237 cterm=NONE
  hi ALEVirtualTextError ctermfg=8 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=8 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleError ctermfg=8 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleWarning ctermfg=8 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=8 ctermbg=NONE cterm=NONE
  hi cOperator ctermfg=6 ctermbg=NONE cterm=NONE
  hi cPreCondit ctermfg=5 ctermbg=NONE cterm=NONE
  hi csAttribute ctermfg=3 ctermbg=NONE cterm=NONE
  hi csClass ctermfg=3 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=5 ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=5 ctermbg=NONE cterm=NONE
  hi csNewDecleration ctermfg=1 ctermbg=NONE cterm=NONE
  hi csType ctermfg=1 ctermbg=NONE cterm=NONE
  hi csUnspecifiedStatement ctermfg=4 ctermbg=NONE cterm=NONE
  hi cssBraces ctermfg=7 ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=5 ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=6 ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=2 cterm=NONE
  hi diffFile ctermfg=1 cterm=NONE
  hi diffNewFile ctermfg=2 cterm=NONE
  hi diffLine ctermfg=4 cterm=NONE
  hi diffRemoved ctermfg=1 cterm=NONE
  hi gitcommitBranch ctermfg=209 ctermbg=NONE cterm=bold
  hi gitcommitComment ctermfg=8 ctermbg=NONE cterm=NONE
  hi gitcommitDiscarded ctermfg=8 ctermbg=NONE cterm=NONE
  hi gitcommitDiscardedFile ctermfg=1 ctermbg=NONE cterm=bold
  hi gitcommitDiscardedType ctermfg=4 ctermbg=NONE cterm=NONE
  hi gitcommitHeader ctermfg=5 ctermbg=NONE cterm=NONE
  hi gitcommitOverflow ctermfg=1 ctermbg=NONE cterm=NONE
  hi gitcommitSelected ctermfg=8 ctermbg=NONE cterm=NONE
  hi gitcommitSelectedFile ctermfg=2 ctermbg=NONE cterm=bold
  hi gitcommitSelectedType ctermfg=4 ctermbg=NONE cterm=NONE
  hi gitcommitSummary ctermfg=2 ctermbg=NONE cterm=NONE
  hi gitcommitUnmergedFile ctermfg=1 ctermbg=NONE cterm=bold
  hi gitcommitUnmergedType ctermfg=4 ctermbg=NONE cterm=NONE
  hi gitcommitUntracked ctermfg=8 ctermbg=NONE cterm=NONE
  hi gitcommitUntrackedFile ctermfg=3 ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=2 ctermbg=237 cterm=NONE
  hi GitGutterChange ctermfg=4 ctermbg=237 cterm=NONE
  hi GitGutterDelete ctermfg=1 ctermbg=237 cterm=NONE
  hi GitGutterChangeDelete ctermfg=5 ctermbg=237 cterm=NONE
  hi htmlBold ctermfg=3 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=7 ctermbg=NONE cterm=NONE
  hi htmlItalic ctermfg=5 ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=7 ctermbg=NONE cterm=NONE
  hi javaOperator ctermfg=4 ctermbg=NONE cterm=NONE
  hi javaScript ctermfg=7 ctermbg=NONE cterm=NONE
  hi javaScriptBraces ctermfg=7 ctermbg=NONE cterm=NONE
  hi javaScriptNumber ctermfg=209 ctermbg=NONE cterm=NONE
  hi jsBuiltins ctermfg=3 ctermbg=NONE cterm=NONE
  hi jsClassDefinition ctermfg=3 ctermbg=NONE cterm=NONE
  hi jsClassFuncName ctermfg=4 ctermbg=NONE cterm=NONE
  hi jsClassMethodType ctermfg=5 ctermbg=NONE cterm=NONE
  hi jsExceptions ctermfg=3 ctermbg=NONE cterm=NONE
  hi jsFuncCall ctermfg=4 ctermbg=NONE cterm=NONE
  hi jsFuncName ctermfg=4 ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=5 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=3 ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=3 ctermbg=NONE cterm=NONE
  hi jsOperator ctermfg=4 ctermbg=NONE cterm=NONE
  hi jsRegexpString ctermfg=6 ctermbg=NONE cterm=NONE
  hi jsReturn ctermfg=5 ctermbg=NONE cterm=NONE
  hi jsStatement ctermfg=5 ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=1 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=2 ctermbg=NONE cterm=NONE
  hi markdownCodeBlock ctermfg=2 ctermbg=NONE cterm=NONE
  hi markdownError ctermfg=7 cterm=NONE
  hi markdownHeadingDelimiter ctermfg=4 ctermbg=NONE cterm=NONE
  hi phpComparison ctermfg=7 ctermbg=NONE cterm=NONE
  hi phpMemberSelector ctermfg=7 ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=6 ctermbg=NONE cterm=NONE
  hi phpParent ctermfg=7 ctermbg=NONE cterm=NONE
  hi pythonInclude ctermfg=5 ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=5 ctermbg=NONE cterm=NONE
  hi pythonRepeat ctermfg=5 ctermbg=NONE cterm=NONE
  hi pythonStatement ctermfg=5 ctermbg=NONE cterm=NONE
  hi rubyAttribute ctermfg=4 ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=3 ctermbg=NONE cterm=NONE
  hi rubyInterpolationDelimiter ctermfg=166 ctermbg=NONE cterm=NONE
  hi rubyRegexp ctermfg=6 ctermbg=NONE cterm=NONE
  hi rubyStringDelimiter ctermfg=2 ctermbg=NONE cterm=NONE
  hi rubySymbol ctermfg=2 ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=209 ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=5 ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=4 ctermbg=NONE cterm=NONE
  hi sassMixing ctermfg=5 ctermbg=NONE cterm=NONE
  hi sassidChar ctermfg=1 ctermbg=NONE cterm=NONE
  hi semshiAttribute ctermfg=7 ctermbg=NONE cterm=NONE
  hi semshiBuiltin ctermfg=5 ctermbg=NONE cterm=NONE
  hi semshiErrorChar ctermbg=1 cterm=NONE
  hi semshiErrorSign ctermfg=1 ctermbg=237 cterm=NONE
  hi semshiFree ctermfg=218 ctermbg=NONE cterm=NONE
  hi semshiGlobal ctermfg=7 ctermbg=NONE cterm=bold
  hi semshiImported ctermfg=3 ctermbg=NONE cterm=NONE
  hi semshiLocal ctermfg=166 ctermbg=NONE cterm=NONE
  hi semshiParameter ctermfg=6 ctermbg=NONE cterm=NONE
  hi semshiParameterUnused ctermfg=117 ctermbg=NONE cterm=underline
  hi semshiSelected ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi semshiSelf ctermfg=1 ctermbg=NONE cterm=NONE
  hi semshiUnresolved ctermfg=3 ctermbg=NONE cterm=underline
  hi SignifySignAdd ctermfg=2 ctermbg=237 cterm=NONE
  hi SignifySignChange ctermfg=4 ctermbg=237 cterm=NONE
  hi SignifySignDelete ctermfg=1 ctermbg=237 cterm=NONE
  hi StartifyBracket ctermfg=8 ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=15 ctermbg=NONE cterm=NONE
  hi StartifyFooter ctermfg=8 ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=2 ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=209 ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=8 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=5 ctermbg=NONE cterm=NONE
  hi StartifySelect ctermfg=6 ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=8 ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=8 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  if get(g:, 'eighties_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=Black cterm=NONE
  hi Cursor ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=DarkGrey cterm=bold
  hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi DiffChange ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi DiffDelete ctermfg=Red ctermbg=DarkGrey cterm=bold
  hi DiffText ctermfg=Blue ctermbg=DarkGrey cterm=bold
  hi Directory ctermfg=Blue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=DarkGrey ctermbg=DarkYellow cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=Green ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Green ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Grey ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermbg=248 guibg=Grey
  hi PmenuThumb ctermbg=15 guibg=White
  hi Question ctermfg=Blue ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Search ctermfg=DarkGrey ctermbg=Yellow cterm=NONE
  hi SignColumn ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLineSel ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi TooLong ctermfg=Red ctermbg=NONE cterm=NONE
  hi Title ctermfg=Blue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=Yellow cterm=NONE
  hi Character ctermfg=Red ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Define ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=Red cterm=NONE
  hi Identifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Include ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Label ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=italic
  hi Structure ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Yellow ctermbg=DarkGrey cterm=italic
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Red ctermbg=NONE cterm=underline
  if !s:italics
    hi Comment cterm=NONE
    hi String cterm=NONE
    hi Todo cterm=NONE
  endif
  if !get(g:, 'eighties_italicize_strings', 1)
    hi String gui=NONE cterm=NONE
  endif
  hi ALEErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=DarkGrey cterm=NONE
  hi ALEInfoSign ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi cOperator ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi cPreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csAttribute ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csNewDecleration ctermfg=Red ctermbg=NONE cterm=NONE
  hi csType ctermfg=Red ctermbg=NONE cterm=NONE
  hi csUnspecifiedStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssBraces ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=Green ctermbg=Black cterm=NONE
  hi diffFile ctermfg=Red ctermbg=Black cterm=NONE
  hi diffNewFile ctermfg=Green ctermbg=Black cterm=NONE
  hi diffLine ctermfg=Blue ctermbg=Black cterm=NONE
  hi diffRemoved ctermfg=Red ctermbg=Black cterm=NONE
  hi gitcommitBranch ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi gitcommitComment ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitDiscarded ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitDiscardedFile ctermfg=Red ctermbg=NONE cterm=bold
  hi gitcommitDiscardedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitHeader ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi gitcommitOverflow ctermfg=Red ctermbg=NONE cterm=NONE
  hi gitcommitSelected ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitSelectedFile ctermfg=Green ctermbg=NONE cterm=bold
  hi gitcommitSelectedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitSummary ctermfg=Green ctermbg=NONE cterm=NONE
  hi gitcommitUnmergedFile ctermfg=Red ctermbg=NONE cterm=bold
  hi gitcommitUnmergedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitUntracked ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitUntrackedFile ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi GitGutterChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi htmlBold ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi htmlItalic ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi javaScript ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptBraces ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptNumber ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsBuiltins ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsClassDefinition ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsClassFuncName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsClassMethodType ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsExceptions ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsFuncCall ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsFuncName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsRegexpString ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi jsReturn ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=Red ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownCodeBlock ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownError ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi markdownHeadingDelimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi phpComparison ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpMemberSelector ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi phpParent ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi pythonInclude ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonRepeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rubyAttribute ctermfg=Blue ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyInterpolationDelimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyRegexp ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi rubyStringDelimiter ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubySymbol ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi sassMixing ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi sassidChar ctermfg=Red ctermbg=NONE cterm=NONE
  hi semshiAttribute ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi semshiBuiltin ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi semshiErrorChar ctermfg=Black ctermbg=Red cterm=NONE
  hi semshiErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi semshiFree ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi semshiGlobal ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi semshiImported ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi semshiLocal ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi semshiParameter ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi semshiParameterUnused ctermfg=LightBlue ctermbg=NONE cterm=underline
  hi semshiSelected ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi semshiSelf ctermfg=Red ctermbg=NONE cterm=NONE
  hi semshiUnresolved ctermfg=Yellow ctermbg=NONE cterm=underline
  hi SignifySignAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi SignifySignChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi StartifyBracket ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=White ctermbg=NONE cterm=NONE
  hi StartifyFooter ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StartifySelect ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=Grey ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'eighties_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=Black cterm=NONE
  hi Cursor ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=DarkGrey cterm=bold
  hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi DiffChange ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi DiffDelete ctermfg=Red ctermbg=DarkGrey cterm=bold
  hi DiffText ctermfg=Blue ctermbg=DarkGrey cterm=bold
  hi Directory ctermfg=Blue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=Black cterm=NONE
  hi FoldColumn ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=DarkGrey ctermbg=DarkYellow cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=Green ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Green ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Grey ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermbg=248 guibg=Grey
  hi PmenuThumb ctermbg=15 guibg=White
  hi Question ctermfg=Blue ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Search ctermfg=DarkGrey ctermbg=Yellow cterm=NONE
  hi SignColumn ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLineSel ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi TooLong ctermfg=Red ctermbg=NONE cterm=NONE
  hi Title ctermfg=Blue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=Yellow cterm=NONE
  hi Character ctermfg=Red ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Define ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=Red cterm=NONE
  hi Identifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Include ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Label ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=italic
  hi Structure ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Yellow ctermbg=DarkGrey cterm=italic
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Red ctermbg=NONE cterm=underline
  if !s:italics
    hi Comment cterm=NONE
    hi String cterm=NONE
    hi Todo cterm=NONE
  endif
  if !get(g:, 'eighties_italicize_strings', 1)
    hi String gui=NONE cterm=NONE
  endif
  hi ALEErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi ALEWarningSign ctermfg=DarkYellow ctermbg=DarkGrey cterm=NONE
  hi ALEInfoSign ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextStyleWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi cOperator ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi cPreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csAttribute ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi csNewDecleration ctermfg=Red ctermbg=NONE cterm=NONE
  hi csType ctermfg=Red ctermbg=NONE cterm=NONE
  hi csUnspecifiedStatement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssBraces ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi cssColor ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi diffAdded ctermfg=Green ctermbg=Black cterm=NONE
  hi diffFile ctermfg=Red ctermbg=Black cterm=NONE
  hi diffNewFile ctermfg=Green ctermbg=Black cterm=NONE
  hi diffLine ctermfg=Blue ctermbg=Black cterm=NONE
  hi diffRemoved ctermfg=Red ctermbg=Black cterm=NONE
  hi gitcommitBranch ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi gitcommitComment ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitDiscarded ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitDiscardedFile ctermfg=Red ctermbg=NONE cterm=bold
  hi gitcommitDiscardedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitHeader ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi gitcommitOverflow ctermfg=Red ctermbg=NONE cterm=NONE
  hi gitcommitSelected ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitSelectedFile ctermfg=Green ctermbg=NONE cterm=bold
  hi gitcommitSelectedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitSummary ctermfg=Green ctermbg=NONE cterm=NONE
  hi gitcommitUnmergedFile ctermfg=Red ctermbg=NONE cterm=bold
  hi gitcommitUnmergedType ctermfg=Blue ctermbg=NONE cterm=NONE
  hi gitcommitUntracked ctermfg=Grey ctermbg=NONE cterm=NONE
  hi gitcommitUntrackedFile ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi GitGutterAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi GitGutterChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi htmlBold ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi htmlItalic ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi htmlTag ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi javaScript ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptBraces ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptNumber ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi jsBuiltins ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsClassDefinition ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsClassFuncName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsClassMethodType ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsExceptions ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsFuncCall ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsFuncName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsOperator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi jsRegexpString ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi jsReturn ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi jsThis ctermfg=Red ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownCodeBlock ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownError ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi markdownHeadingDelimiter ctermfg=Blue ctermbg=NONE cterm=NONE
  hi phpComparison ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpMemberSelector ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi phpParent ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi pythonInclude ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonOperator ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonRepeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi pythonStatement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rubyAttribute ctermfg=Blue ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyInterpolationDelimiter ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi rubyRegexp ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi rubyStringDelimiter ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubySymbol ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=Blue ctermbg=NONE cterm=NONE
  hi sassMixing ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi sassidChar ctermfg=Red ctermbg=NONE cterm=NONE
  hi semshiAttribute ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi semshiBuiltin ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi semshiErrorChar ctermfg=Black ctermbg=Red cterm=NONE
  hi semshiErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi semshiFree ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi semshiGlobal ctermfg=LightGrey ctermbg=NONE cterm=bold
  hi semshiImported ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi semshiLocal ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi semshiParameter ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi semshiParameterUnused ctermfg=LightBlue ctermbg=NONE cterm=underline
  hi semshiSelected ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi semshiSelf ctermfg=Red ctermbg=NONE cterm=NONE
  hi semshiUnresolved ctermfg=Yellow ctermbg=NONE cterm=underline
  hi SignifySignAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi SignifySignChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi StartifyBracket ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifyFile ctermfg=White ctermbg=NONE cterm=NONE
  hi StartifyFooter ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifyHeader ctermfg=Green ctermbg=NONE cterm=NONE
  hi StartifyNumber ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi StartifyPath ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StartifySelect ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi StartifySlash ctermfg=Grey ctermbg=NONE cterm=NONE
  hi StartifySpecial ctermfg=Grey ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                #2d2d2d                0        Black
" Color: red                  #f2777a                1        Red
" Color: green                #99cc99                2        Green
" Color: yellow               #ffcc66                3        Yellow
" Color: blue                 #6699cc                4        Blue
" Color: magenta              #cc99cc                5        Magenta
" Color: cyan                 #66cccc                6        Cyan
" Color: white                #d3d0c8                7        LightGrey
" Color: brightblack          #747369                8        Grey
" Color: brightred            #f2777a                9        LightRed
" Color: brightgreen          #99cc99                10       LightGreen
" Color: brightyellow         #ffcc66                11       LightYellow
" Color: brightblue           #6699cc                12       LightBlue
" Color: brightmagenta        #cc99cc                13       LightMagenta
" Color: brightcyan           #66cccc                14       LightCyan
" Color: brightwhite          #f2f0ec                15       White
" Color: orange               #f99157                209      DarkYellow
" Color: darkorange           #d27b53                166      DarkYellow
" Color: darkgrey             #393939                237      DarkGrey
" Color: grey                 #515151                239      Grey
" Color: brightgrey           #a09f93                247      LightGrey
" Color: lightblue            #87d7ff                117      LightBlue
" Color: pink                 #ffafd7                218      Magenta
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
