#!/bin/zsh
. icons
# A ordem em que as partições são especificadas definem a ordem que os $iconS e $colorFSIconS 
# correspondentes a cada partição tem que ser informado
# Especificar as partições que quer imprimir separadas por espaços;
partitionS=(/dev/sdb2 /dev/sda3)
# Especificar os ícones em ordem com a $partitionS, separadas por espaços;
FSiconS=(''  '') #       🖴
# Especificar as cores em ordem com os $iconS, separadas por espaços;
#colorFSIconS=("$color10" "$color9")
# Espefificar as fontes que quer Usar, a polybar é baseada em font-0
# para fonte-1 escolha "2";
fontFSIconS=("13" "12")
# Altere [ sed 's/'$HOME'//g ] por [ sed 's/\/home\/SeuUser//g ] 
base="$(df -h $partitionS[@] |awk '{print " "$6" "$5" "$3}'|sed '1d'|sed 's/\/home\/losao\///g')"

for (( i = 1; i <= $((${#FSiconS[@]})); i++ ))
{
	echo -ne " %{F${colorFSIconS[${i}]}}%{T${fontFSIconS[${i}]}}${FSiconS[$i]}%{F- T-}$(sed -n ''$i'p' <<< "$base") "
}
