#!/bin/zsh
br ()
{
  setxkbmap -model abnt2 -layout br -variant abnt2
  # setxkbmap -model abnt2 -layout br -variant latin
}
br2 ()
{
  setxkbmap -model abnt2 -layout br
}
us ()
{
  setxkbmap -model us -layout us
}
$@