#!/bin/zsh
namewm=$(wmctrl -m |grep -i NAME|sed 's/.*: //')
export config=$path_polybar/config.$namewm
export bars=("dock") #altere para o nome suas bars ela precisam estar a posição bottom.

pkill -9 polybar
if [[ -n $monitor2 ]]; then
	polybar -c $config dock -q -r &> /dev/null &
	polybar -c $config taskbar -q -r &> /dev/null &
	polybar -c $config taskbar2 -q -r &> /dev/null &
	polybar -c $config dock2 -q -r &> /dev/null &
else
	polybar -c $config dock -r &> /dev/null &
	polybar -c $config taskbar -r &> /dev/null &
fi

