#!/bin/zsh
#namewm=$(wmctrl -m |grep -i NAME|sed 's/.*: //')

#config=$path_polybar/config.$namewm

if [[ ${${(s: :)${(f)"$(wmctrl -m)"}[1]}[2]} == "bspwm" ]]; then
	config=/hdbkp/dots/polybar/config.bspwm
else
	config=/hdbkp/dots/polybar/config.qtile
fi

pkill -9 polybar
if [[ -n $monitor2 ]]; then
	polybar -c $config dock -q -r &> /dev/null &
	polybar -c $config taskbar -q -r &> /dev/null &
	polybar -c $config taskbar2 -q -r &> /dev/null &
	polybar -c $config dock2 -q -r &> /dev/null &
else
	#polybar -c $config dock -r &> /dev/null &
	polybar -c $config taskbar -r &> /dev/null &
fi

