#!/bin/zsh
# Include cores externas
. /hdbkp/dots/temas/colors.zsh

ThemeCustom="* {
background:                  $background ;
background-color:            $background ;
foreground:                  $foreground ;
border-color:                $color4 ;
separatorcolor:              $background ;
scrollbar-handle:            $background ;

normal-background:           $background;
normal-foreground:           $foreground;
alternate-normal-background: $background;
alternate-normal-foreground: $foreground;
selected-normal-background:  $background;
selected-normal-foreground:  $color13;

active-background:           $background;
active-foreground:           $color1;
alternate-active-background: $background;
alternate-active-foreground: $color1;
selected-active-background:  $color4;
selected-active-foreground:  $color1;

urgent-background:           $background;
urgent-foreground:           $color13;
alternate-urgent-background: $background;
alternate-urgent-foreground: $color13;
selected-urgent-background:  $color4;
selected-urgent-foreground:  $color3;
}"

buttonSelected="button.selected {
background-color: $foreground;
text-color:       $background;
}"

cmdSearchYT () { mp $@ }
#########################################################################################################
#  PROGRAMA MODELO
#########################################################################################################
# Toggle para gravar a tela com simplescreenrecorder não configura nada, 
# toda configuração para gravação é feita em ~/.ssr/settings.ini pelo user;
# requer xdotool
ssr ()
{
	if { ! grep '[s]implescreenrecorder --start-hidden --no-systray' <<< `ps aux` }; then
		simplescreenrecorder --start-hidden --no-systray --start-recording &
		sleep 0.5
		ntfy "Recording Started" &
	else
		ntfy "Recording Stoped" &
		nohup $(sleep 2 && pkill simplescreenrec) &> /dev/null &
		exec xdotool key super+shift+alt+ctrl+r
	fi
}

searchYT ()
{
	mainYT ()
	{		
		base="$(youtube-dl --get-title --get-id --get-duration "ytsearch$qt_return:"$@"" |xargs -0)"

		control=1
		controllerT=1
		controllerI=1
		controllerD=1

		typeset -A Titles IDs Durations

		for element in ${${(f)base}[@]}
		{
			case $control in
				1 )
					control=$(($control+1))
					Titles+=([$controllerT]=$element)
					controllerT=$(($controllerT+1)) ;;
				2 ) 
					control=$(($control+1))
					IDs+=([$controllerI]="https://www.youtube.com/watch?v=$element")
					controllerI=$(($controllerI+1)) ;;
				3 ) 
					control=1
					Durations+=([$controllerD]=$element)
					controllerD=$(($controllerD+1)) ;;
			esac
		}

		if [[ $#Titles[@] -gt 1 ]]; then
			for (( i = 1; i <= $#IDs; i++ )); do
		 		printf '%-80s %10s %20s' "${Titles[$i]}" "${Durations[$i]}" "${IDs[$i]} ;"
			done
		else
			 printf '%-80s %10s %20s' "${Titles}" "$Durations" "${IDs}"
		fi	  
	}

	finish ()
	{
		[[ -n $parms ]] && \
			{
				[[ $loop == "false"	]] && {	mainYT "$parms" |read base }

				lines=$(($qt_return+1))
				columns=1

				struct $base | read url

				[[ -n $url ]] && \
					{ 
						cmdSearchYT "${${(s: :)url}[-1]}" &> /dev/null &
						loop="true"
						finish
					} || \
						{
							exit 0
						}
			} || \
				{
					exit 0
				}
	}
	prompt="Retorno (< 30)"
	lines=2
	lH="false"
	struct "$prompt" |read qt_return
	prompt="Search on YouTube:"
	parms=$(struct "$prompt")

	loop="false"

	finish
}

cmd ()
{
	helpCMD () #
	{
	  funcoes=$(grep "()" $(print ~/.local/bin/*)|sed 's/() *{*//g'|sed 's/.*\///g;s/:/ /g')
	  <<< $funcoes|sort
	}
    source ~/.local/bin/allfunctions
	if [[ ! -e /tmp/cmd ]]; then
		< ~/.zhistory |sort --unique > /tmp/cmd
		helpCMD >> /tmp/cmd
		print -l /usr/bin/* >> /tmp/cmd
	else
		[[ ~/.zhistory -nt /tmp/cmd ]] &&
			{ < ~/.zhistory |tail -100 |sort --unique >> /tmp/cmd }
	fi
	prompt="  ® "
	lH="true"
	location=2
	width=45
	yoffset=1990
	iD="false"
	[[ -n $fontText ]] && \
		{
			fontOrigin=$font
			font=$fontText
		}
	struct $(< /tmp/cmd|sed 's/$/;/g') |read CMD
	if [[ -n $CMD ]];then
		zsh -c $(source ~/.zprofile; ${CMD}) && ntfy " FALSE  => $CMD " || ntfy " TRUE   $CMD"
	fi
}

#########################################################################################################
#  DEFINIÇÕES DAS ESTRUTURAS
#########################################################################################################
struct ()
{
	defs
	[[ -z $1 && -n $modi ]] && \
		{ 
			rofi -pid $pidFile -no-plugins -no-config -font "$font" "$base[@]" 
		} || \
			{
				# base+=(-kb-select-1 1 -kb-select-2 2 -kb-select-3 3 -kb-select-4 4 -kb-select-5 5 -kb-select-6 6 \
				# -kb-select-7 7 -kb-select-8 8 -kb-select-9 9 -kb-select-10 0)
				echo "$@" | rofi -dmenu -sep ';' -l $linesRet "$base[@]" -pid $pidFile -no-plugins -no-config -font "$font" -format 'f'
			}
}
defs ()
{
	iconTheme=${${(s:=:)${(f)"$(< $HOME/.config/gtk-3.0/settings.ini)"}[3]}[2]}
	# [[ -z $font ]] && font="${${(s:=:)${(f)"$(< $HOME/.config/gtk-3.0/settings.ini)"}[4]}[2]}"
	[[ -z $font ]] && font="M+ 2m 16"
	rofiIcon=""
	layoutHorizontal='#listview { layout: horizontal; }'
	inputbarDisable='#inputbar { enabled: false; }'
	[[ -n $active ]] && base+=(-a $active) 
	[[ -n $bw ]] && base+=(-bw $bw) 
	[[ -n $columns ]] && base+=(-columns $columns) 
	[[ -n $modi ]] && base+=(-modi window,run,ssh,drun,combi) 
	[[ -n $height ]] && base+=(-eh $height)	 
	[[ -n $lines ]] && base+=(-lines $lines) && linesRet=$lines 
	[[ -z $linesRet ]] && linesRet=25 
	[[ -n $linepadding ]] && base+=(-line-padding $linepadding)
	[[ -n $location ]] && base+=(-location $location)	 
	[[ -n $prompt ]] && base+=(-p $prompt) 
	[[ -n $padding ]] && base+=(-padding $padding) 
	[[ -n $radius ]]&& base+=(-Theme-str '#window { border-radius: '$radius'px; }') 
	[[ -n $selRow ]] && base+=(-selected-row $selRow) 
	[[ -n $show ]] && base+=(-show $show) 
	[[ -n $title ]] && base+=(-window-title $title) || base+=(-window-title lrofi)
	[[ -z $terminal ]] && base+=(-terminal kitty) 
	[[ -n $Ctheme ]] && base+=(-theme $Ctheme) || base+=(-Theme-str ''$ThemeCustom'')
	[[ -n $urgent ]] && base+=(-u $urgent)
	[[ -n $width ]] && base+=(-width $width) 
	[[ -n $xoffset ]] && base+=(-xoffset "$xoffset") 
	[[ -n $yoffset ]] && base+=(-yoffset "$yoffset") 
	[[ $fullscreen == "true" ]] && base+=(-fullscreen)
	[[ $hS == "true" ]] && base+=(-hide-scrollbar)
	[[ $iD == "true" ]] && base+=(-Theme-str "$inputbarDisable")
	[[ $lH == "true" ]] && base+=(-Theme-str ''$layoutHorizontal'' -hide-scrollbar) ; example+=(-Theme-str ''$layoutHorizontal'' -hide-scrollbar)
	[[ $nW == "true" ]] && base+=(-normal-window) ; example+=(-normal-window)
	[[ $normalwindow == "true" ]] && base+=(-normal-window) 
	[[ $si != "false" ]] && base+=(-show-icons -icon-Theme $iconTheme) 
}
##########################################################################################################
#  TRATATIVA DE ARGUMENTOS
#########################################################################################################
. allopts --location: -l: -width: -w: -width2: -w2: -height: -eh: -bw: -xoffset: -x: -yoffset: -y: -padding: -p: -fontIcons: -fi: \
-fontEntry: -fe: -fontText: -ft: -font: -f: -Theme: -t: -help! -h! -fullscreen! -fs! -lines: -ln: -columns: -cl: \
-Themestr: -ts: -inputbarDisable! -iD! -layoutHorizontal! -lH! -normalwindow! -nW! -modi: -m: -show: -s: -showIcons: \
-si: -prompt: -pt: -linepadding: -lnp: -radius: -r: -terminal: -tt: -active: -a: -urgent: -u: -selected-row: -selRow: \
-sr: -ttl: -title: -hS! -hide-scrollbar! $@

for i in $@
{
	[[ "$ARGREFUSED" =~ "$i" ]] && shift || args+=("$i")
}

[[ -n $ARGUMENTOS[fullscreen] || -n $ARGUMENTOS[fs] ]] && fullscreen="true" || fullscreen="false"
[[ -n $ARGUMENTOS[inputbarDisable] || -n $ARGUMENTOS[iD] ]] && iD="true" || iD="false"
[[ -n $ARGUMENTOS[layoutHorizontal] || -n $ARGUMENTOS[lH] ]] && lH="true" || lH="false"
[[ -n $ARGUMENTOS[normalwindow] || -n $ARGUMENTOS[nW] ]] && nW="true" || nW="false"
[[ -n $ARGUMENTOS[showIcons] || -n $ARGUMENTOS[si] ]] && sI="true" || sI="false"
[[ -n $ARGUMENTOS[hidescrollbar] || $ARGUMENTOS[hS] ]] && hS="true" || hS="false"

for x in $ARGUMENTOS[@] 
{  
	case $x in
		$ARGUMENTOS[bw] ) bw="$x" ;;
		$ARGUMENTOS[active] || $ARGUMENTOS[a] ) active="$x" ;;
		$ARGUMENTOS[columns] || $ARGUMENTOS[cl] ) columns="$x" ;;
		$ARGUMENTOS[font] || $ARGUMENTOS[f] ) font="$x" ;;
		$ARGUMENTOS[fontIcons] || $ARGUMENTOS[fi] ) fontIcons="$x" ;;
		$ARGUMENTOS[fontEntry] || $ARGUMENTOS[fe] ) fontEntry="$x" ;;
		$ARGUMENTOS[fontText] || $ARGUMENTOS[ft] ) fontText="$x" ;;
		$ARGUMENTOS[height] || $ARGUMENTOS[eh] ) height="$x" ;;
		$ARGUMENTOS[help] || $ARGUMENTOS[h] ) help & exit 0 ;;
		$ARGUMENTOS[lines] || $ARGUMENTOS[ln] ) lines="$x" ;;
		$ARGUMENTOS[linepadding] || $ARGUMENTOS[lnp] ) linepadding="$x" ;;
		$ARGUMENTOS[location] || $ARGUMENTOS[l] ) location="$x" ;;
		$ARGUMENTOS[modi] || $ARGUMENTOS[m] ) modi="$x" ;;
		$ARGUMENTOS[prompt] || $ARGUMENTOS[pt] ) prompt="$x" ;;
		$ARGUMENTOS[padding] || $ARGUMENTOS[p] ) padding="$x" ;;
		$ARGUMENTOS[radius] || $ARGUMENTOS[r] ) radius="$x" ;;
		$ARGUMENTOS[show] || $ARGUMENTOS[s] ) show="$x" ;;
		$ARGUMENTOS[selectedrow] || $ARGUMENTOS[selRow] || $ARGUMENTOS[sr] ) selRow="$x" ;;
		$ARGUMENTOS[terminal] || $ARGUMENTOS[tt] ) terminal="$x" ;;
		$ARGUMENTOS[title] || $ARGUMENTOS[ttl] ) title="$x" ;;
		$ARGUMENTOS[theme] || $ARGUMENTOS[t] ) Ctheme="$x" ;;
		$ARGUMENTOS[urgent] || $ARGUMENTOS[u] ) urgent="$x" ;;
		$ARGUMENTOS[xoffset] || $ARGUMENTOS[x] ) xoffset="$x" ;;
		$ARGUMENTOS[width] || $ARGUMENTOS[w] ) width="$x" ;;
		$ARGUMENTOS[width2] || $ARGUMENTOS[w2] ) width2="$x" ;;
		$ARGUMENTOS[yoffset] || $ARGUMENTOS[y] ) yoffset="$x" ;;
	esac
}

#########################################################################################################
#  EXECUÇÃO
#########################################################################################################
# NEWS FUNCTIONS , SERÃO OS MODELOS:
example_pl () { defs; lrofi -f $font -p 20 -l 0 -y 115 -x -92 -w 15 player plistrofi &>/dev/null & }
example_player () { defs; lrofi -f $font -lH -iD -p 20 -l 0 -y 115 -x -92 -w 15 player &>/dev/null & }
example_drun () { defs; lrofi -f $font -x -25 -y 92 -w 15 -bw 8 -radius 25 -modi combi -show drun }

pidFile=$(mktemp)
. ~/.zshrc
# . $path_scripts/icons
# . $path_colors/colors.zsh

if [[ -z $args && -z $modi ]]; then
	lH="true"; iD="true"; main
elif [[ -z $args && -n $modi ]]; then
	struct
else
	$args
fi

# Exclui o arquivo temporario
rm -f $pidFile


