#!/bin/zsh
# projeto para automatizar a criaçao de markdowns

paragrafo ()
{
	printf %b $@ |sed 's/$/\<br\>/g'
}
negrito ()
{
	printf %b '<strong>'$@'</strong>'
}
italico ()
{
	printf %b '<em>'$@'</em>'
}
negrito.italico ()
{
	printf %b '<strong><em>'$@'</strong></em>'
}
codigo ()
{
	printf %b '`'$@'`'
}
bloco ()
{
	printf %b $@ | sed 's/^/\n\> /g'
}
bloco2 ()
{
	printf %b $@ | sed 's/^/\n\>\> /g'
}
titulo ()
{
	printf %b '<h1>'$@'</h1>'
}
sub.titulo ()
{
	printf %b '<h2>'$@'</h2>'
}
capitulo ()
{
	printf %b '<h3>'$@'</h3>'
}
sub.capitulo ()
{
	printf %b '<h4>'$@'</h4>'
}
lista.ordenada ()
{
	printf %b '<ol>'$(for x in $@; do; printf %b '<li>'$x'</li>';done)'</ol>'
}
lista.desordenada ()
{
	printf %b '<ul>'$(for x in $@; do; printf %b '<li>'$x'</li>';done)'</ul>'
}
imagem ()
{
	# passar $1 como $text e $2 como $imagem
	printf %b '!['$text']('$imagem')'
}
help () #
{
	for x in ${"$(grep ' ()' $path_scripts/mkdowncreate |grep -v '#')"//\(\)/}
	{
		base+=($x)
	}
	<<< "${base[@]}"
}
