#!/bin/zsh
. allopts -t: --t: -time: --time: -h! --h! -help! --help! -i: --i: -icon: --icon: -m: --m: -msg: --msg: $@

for i in $@
{
	[[ "$ARGREFUSED" =~ "$i" ]] && shift
}

for x in $ARGUMENTOS[@] 
{  
	case $x in
		$ARGUMENTOS[time] || $ARGUMENTOS[t] ) time=$x ;;
		$ARGUMENTOS[icon] || $ARGUMENTOS[i] ) icon=$x ;;
		$ARGUMENTOS[msg] || $ARGUMENTOS[m] ) msg=$x ;;
		$ARGUMENTOS[help] || $ARGUMENTOS[h] ) 
		<<- help
		
		O script vai procurar pelo arquivo \$HOME/.config/gtk-3.0/settings.ini, consultá-lo sobre qual o tema de ícones em seguida procura em \$HOME/.icons/[tema definido em settings.ini] e verifica se o valor passado pelo parâmetro `tput bold`-i/--i/-icon/--icon`tput sgr0` corresponde ao nome de algum ícone, então o usa, caso não corresponda ou o arquivo settings não seja encontado, usará o ícone padrao de notificação "bell",


		help
		exit 0 ;;
	esac
}

[[ -n $@ ]] && \
	case $@ in
		* ) 
			<<- error
			`tput bold; tput setaf 1`opção não cadastrada `tput setaf 7`$@
			`tput bold; tput setaf 2`Consulte:`tput sgr0`
				`tput setaf 2; tput bold`notify`tput sgr0` --help | -help | --h | -h 

			error
			exit 0 ;;
	esac
Icon="${${(f)"$(print -l $HOME/.icons/${${(s:=:)${(f)"$(< ~/.config/gtk-3.0/settings.ini)"}[3]}[2]}/**/*$icon*)"}[1]}"
[[ -z $Icon ]] && Icon=bell
[[ -z $time ]] && time=5000
[[ -z $msg ]] && msg="Voce precisa indicar a mensagem"
dunstify -t "$time" -i "$Icon" "$msg"

