#!/bin/zsh

verificar ()
{
	
	base ()	{ bspc query --tree -m |sed 's/}\|{\||\|]\|\[//g;s/,/\n/g;s/"//g;s/desktops:name/desktops\nname/' }
	desktop.focused () { bspc query --desktops --node --names }
	node.focused () {  }
	alters () {	[[ ${baseOld} != ${baseNew} ]] }
	$@
}

tabbed ()
{
	baseOld=""
	bspSocket=$(echo /tmp/bspwm_*)
	baseNew=$(verificar base)


	while true; do
		verificar alters && \
			{ 
				dunstify -t 1000 "ALTERAÇÃO NAS JANELAS" & 
				baseOld=$baseNew
			}
		sleep 0.5
		baseNew=$(verificar base)
	done	
}

