#!/bin/zsh
node.id ()
{
    . /hdbkp/taskbar.test/taskbar.conf
    . /hdbkp/dots/temas/colors.zsh

    font="Iosevka Term SS07 12"

    <<< ${${(s:|:)"$(\
        while read line; do; 
            print -f '%s\n'              \
                "${${(s: :)line}[2]}"    \
                " ${${(s: :)line}[4]} "  \
                "${${(s: :)line}[5]}"    \
                " ${${(s: :)line}[3]}  " \
                "$font"                  \
                "${colorsIcons[${${(s: :)line}[5]}]:-$color8}"
        done < /tmp/taskbar |
        yad                                 \
            --title="Windows"               \
            --list                          \
                --no-headers                \
                --column ID                 \
                --column ICON               \
                --column PRGM               \
                --column WK                 \
                --column @font@             \
                --column @fore@             \
                --hide-column=1             \
                --search-column=3           \
                --on-top                    \
                --borders=15                \
                --geometry=450x400+40+120   \
                --grid-lines both           \
                --text-align center         \
                --no-buttons 2>/dev/null    
    )"}[1]} 
}

node.stk ()
{

    id="$(node.id)"
    base=`bspc query -n $id -T |sed 's/{\|}\|"//g;s/,y/ y/g;s/,/\n/g;s/constraints:\|client://g;s/x://g;s/ y:/x/g'` 

    declare -A nodeinfo
        for i in ${(f)base}
            nodeinfo[${${(s#:#)i}[1]}]=${${(s#:#)i}[2]}
    [[ $nodeinfo[sticky] == false ]] && bspc node $id --flag sticky=on ||  bspc node $id --flag sticky=off 
}

node.focus ()
{
    id="$(node.id)"
    base=`bspc query -n $id -T |sed 's/{\|}\|"//g;s/,y/ y/g;s/,/\n/g;s/constraints:\|client://g;s/x://g;s/ y:/x/g'` 

    declare -A nodeinfo
        for i in ${(f)base}
            nodeinfo[${${(s#:#)i}[1]}]=${${(s#:#)i}[2]}
    [[ $nodeinfo[hidden] == false ]] && bspc node $id -f || { bspc node $id --flag hidden=off; bspc node $id -f }
}

seletor4 ()
{
	#--expand-column=1,2,3,4
	yad --list --wrap \
	--column=WS --column=ID --column=WK --column=IC --column=PGR --column=TITLE \
	--selectable-labels --search-column=5 \
	--text-align=center --regex-search \
	--geometry=800x320 --borders=5 $@
}

gap ()
{
	bspc config window_gap $@
}

gap.hori ()
{
	bspc config top_padding $@ && bspc config bottom_padding $@
}

gap.vert ()
{
	bspc config right_padding $@ && bspc config left_padding $@
}
gap.geral ()
{
	bspc config top_padding $1 && bspc config bottom_padding $1
	bspc config right_padding $2 && bspc config left_padding $2
	bspc config window_gap $3
}
border.width ()
{
	bspc config border_width $@
}
border.color.focused ()
{
	bspc config focused_border_color $@
}
border.color.normal ()
{
	bspc config normal_border_color $@
	bspc config active_border_color $@
	bspc config presel_feedback_color $@
}
clearmodifiers ()
{
	xdotool keydown --clearmodifiers super && sleep 1 && xdotool keyup --clearmodifiers super
}
restart ()
{
	pkill polybar 2>/dev/null && sleep 0.5
	taskbar stop 2>/dev/null && sleep 0.5
	wq gpuinfo stop 2>/dev/null && sleep 0.5
	wq weatcher stop 2>/dev/null && sleep 0.5
	picomtoggle 2>/dev/null && sleep 0.5
	pkill redshift 2>/dev/null && sleep 0.5
	pkill dunst 2>/dev/null && sleep 0.5
	pulseaudio-equalizer disable &>/dev/null && sleep 0.5
	bspc wm --restart
}

$@
