#!/bin/zsh
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
helpwq () { < $path_scripts/mn.zsh |sed 's/^\!//g' }
help ()
{
  funcoes=$(grep "()" $(print $path_scripts/*.zsh)|sed 's/() *{*//g')
  sed 's/.*\:/!wq /g' <<< $funcoes|sort
}
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
# Caso não esteja usando a minha conf do bspwm descomente as linhas abaixo abaixo e altere
# 'caminho' pelo local onde está o repositório: 
declare -x path_dots=$HOME/hdbkp/dots
declare -x path_scripts=$path_dots/scripts
declare -x path_polybar=$path_dots/polybar
declare -x path_colors=$path_dots/temas

# Caso não use o taskbar.zsh não há necessidade da linha abaixo:
declare -x bd=/tmp/taskbar

# Para incluir variáveis globais dinâmicas, necessário para $wq mn $wq cmd $mp.command
. $path_scripts/icons.zsh # Todas as funções criadas para o shell
. $path_colors/colors.zsh # Import das cores do tema.
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
[[ -z $@ ]] && return 0 || \
  case $@ in
    help* )
      $@;;
    capscreen* )
      . $path_scripts/screencap.zsh
      shift
      $@;;
    notif* || ntf* )
      . $path_scripts/notify.zsh
      $@ 2>/dev/null;;
    fetch* )
      $path_scripts/fetch.zsh $@ 2>/dev/null;;
    theme* )
      . $path_scripts/theme.zsh
      $@ &>/dev/null;;
    tradutor* )
      . $path_scripts/tradutor.zsh
      $@;;
    color* )
      . $path_scripts/color.zsh
      $@;;
    rede* )
      . $path_scripts/rede.zsh
      $@;;
    rofi* )
      . $path_scripts/rofi.zsh
      $@;;
    picom* )
      $path_scripts/picom.zsh;;
    process* )
      $path_scripts/process.zsh $2;;
    bar* )
      . $path_scripts/bar.zsh
      $@;;
    keyboard* )
      . $path_scripts/keyboard.zsh
      $@;;
    launch* )
      . $path_scripts/launch.zsh
      $@ 2>/dev/null;;
    dd* )
      . $path_scripts/downloads.zsh
      $@;;
    gpu* )
      . $path_scripts/gpuinfo2.zsh
      $@;;
    weatcher* )
      $path_scripts/weatcher.zsh $2 2>/dev/null;;
    install* )
      . $path_scripts/service.zsh
      $@;;
    app* )
      . $path_scripts/apps.zsh
      $@;;
    mp.* || mp* )
      . /home/losaoall/hdbkp/projetos/shell/mpvd/mpv.zsh
      $@;;
    cca* || calc* )
      . $path_scripts/calculadora.zsh
      { init 0 2 } &>/dev/null &;;
    gap.* || bsp.* || node* || wm* || nd* || cap.id )
      . $path_scripts/wm.zsh
      $@;;
    lt* || cmd* || mn* || proc || shll* || seletor* || cl* || sf* || msg* )
      . $path_scripts/yads.zsh
      "$@" ;; # &>/dev/null;;
  esac
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
